name: Publish branch develop to dev.exp-gen.pradilux.com
on:
  push:
    branches:
      - develop
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 2
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ${( secrets.FTP_SERVER )}
        ftp-username: ${( secrets.FTP_USERNAME_DEV )}
        ftp-password: ${( secrets.FTP_PASSWORD_DEV )}
